/* ================================================================
   Auto-generated by calculateMPCMatrices.py
   2026-04-28 23:11:22
   Source files : Data/heater1_fanoff.csv,  Data/heater2_fanoff.csv,  Data/heater1_fanon.csv,  Data/heater2_fanon.csv
   Runs stacked : 4/4  (fan-on + fan-off averaged for disturbance robustness)
   Tuning       : Q=50.0  R=0.5  N=20  Q_noise=0.1  R_noise=1.0

   Paste the struct below into controller_mosfet.ino,
   replacing the existing MIMO_SMOC controller = { ... }; block.
   ================================================================ */

MIMO_SMOC controller = {
  // KX -- state feedback gain  (Q=50.0, R=0.5, N=20)
  {
   { -5.7848f,  -1.3932f},
   {  1.0690f,  -6.4211f}},
  // KU1 -- input smoothness gain
  {
   {  0.3591f,   0.0229f},
   {  0.0229f,   0.4303f}},
  // KYD -- trajectory tracking gain  [2 x 40]
  {
   {  1.7917f,   0.2538f,   1.8747f,   0.3349f,   1.3323f,   0.3095f,   0.7351f,   0.2347f,   0.3002f,   0.1510f,   0.0545f,   0.0804f,  -0.0500f,   0.0309f,  -0.0727f,   0.0019f,  -0.0593f,  -0.0116f,  -0.0370f,  -0.0151f,  -0.0180f,  -0.0134f,  -0.0058f,  -0.0097f,   0.0004f,  -0.0060f,   0.0025f,  -0.0031f,   0.0026f,  -0.0011f,   0.0019f,  -0.0000f,   0.0011f,   0.0005f,   0.0005f,   0.0006f,  -0.0000f,   0.0006f,  -0.0004f,   0.0005f},
   { -0.3903f,   1.4378f,  -0.3837f,   1.7407f,  -0.2487f,   1.4866f,  -0.1172f,   1.0480f,  -0.0318f,   0.6265f,   0.0089f,   0.3051f,   0.0203f,   0.0979f,   0.0176f,  -0.0143f,   0.0108f,  -0.0604f,   0.0047f,  -0.0675f,   0.0010f,  -0.0561f,  -0.0008f,  -0.0389f,  -0.0012f,  -0.0230f,  -0.0009f,  -0.0110f,  -0.0006f,  -0.0033f,  -0.0003f,   0.0008f,  -0.0001f,   0.0025f,   0.0000f,   0.0028f,   0.0000f,   0.0025f,   0.0000f,   0.0020f}},
  // Kalman L -- observer gain  (Q_noise=0.1, R_noise=1.0)
  {
   {  0.2664f,   0.0022f},
   {  0.0022f,   0.2684f}},
  // Model A -- discrete state transition  (averaged across fan on/off)
  {
   {  0.9938f,   0.0052f},
   {  0.0018f,   0.9972f}},
  // Model B -- input actuation
  {
   {  0.0506f,  -0.0118f},
   {  0.0050f,   0.0332f}},
  // Model C -- output mapping (identity: we measure both states)
  {
   {  1.0000f,   0.0000f},
   {  0.0000f,   1.0000f}},
  {0.0f, 0.0f},  // x_hat  (observer state, starts at zero)
  {0.0f, 0.0f},  // u_prev (previous input, starts at zero)
  {0.0f, 0.0f}   // setpoint (degrees C, set via Serial)
};

/* ================================================================ */